version: "3"
services:
 nginx:
  restart: always
  build:
   dockerfile: Dockerfile
   context: ./nginx
  ports:
   - "80:80"
 worker:
  build:
   dockerfile: Dockerfile
   context: ./worker
  environment:
   - REDIS_HOST=redis
   - REDIS_PORT=6379
 postgres:
  image: "postgres:latest"
  environment:
   - POSTGRES_PASSWORD=postgres_password
 redis:
  image: "redis:latest"
 app:
  build:
   dockerfile: Dockerfile
   context: ./flask
  volumes:
   - ./flask:/app
  environment:
   - REDIS_HOST=redis
   - REDIS_PORT=6379
   - PGUSER=postgres
   - PGHOST=postgres
   - PGDATABASE=postgres
   - PGPASSWORD=postgres_password
   - PGPORT=5432
  expose:
   - 5000
